import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Layout } from './components/Layout';

import { Anybody } from 'next/font/google';
import Script from 'next/script';

const anybody = Anybody({
  variable: '--font-anybody',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Script src='https://unpkg.com/@phosphor-icons/web@2.1.1' />

      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anybody.variable} antialiased`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
